language: php

php:
  - 8.1
  - 8.2
  - 8.3
  - 8.4

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || true

before_script:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini || true
  - composer self-update
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --configuration phpunit.xml
